/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package simulator;

/**
 *
 * @author a120134
 */
public class TabelaP extends javax.swing.JFrame {

    /**
     * Creates new form TabelaP
     */
    public TabelaP() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Hidrogênio = new javax.swing.JLabel();
        Lítio = new javax.swing.JLabel();
        Sódio = new javax.swing.JLabel();
        Potássio = new javax.swing.JLabel();
        Rubídio = new javax.swing.JLabel();
        Césio = new javax.swing.JLabel();
        Frâncio = new javax.swing.JLabel();
        _Copia = new javax.swing.JLabel();
        ElementoLabel = new javax.swing.JLabel();
        ElementTextBox = new javax.swing.JTextField();
        ConfirmButton = new javax.swing.JButton();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Hidrogênio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HidrogênioMouseClicked(evt);
            }
        });
        getContentPane().add(Hidrogênio, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 55, 46, 55));

        Lítio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LítioMouseClicked(evt);
            }
        });
        getContentPane().add(Lítio, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 110, 46, 55));

        Sódio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SódioMouseClicked(evt);
            }
        });
        getContentPane().add(Sódio, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 166, 46, 55));

        Potássio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PotássioMouseClicked(evt);
            }
        });
        getContentPane().add(Potássio, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 221, 46, 55));

        Rubídio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RubídioMouseClicked(evt);
            }
        });
        getContentPane().add(Rubídio, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 276, 46, 55));

        Césio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CésioMouseClicked(evt);
            }
        });
        getContentPane().add(Césio, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 331, 46, 55));

        Frâncio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FrâncioMouseClicked(evt);
            }
        });
        getContentPane().add(Frâncio, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 386, 46, 55));

        _Copia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                _CopiaMouseClicked(evt);
            }
        });
        getContentPane().add(_Copia, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 46, 55));

        ElementoLabel.setText("Elemento:");
        getContentPane().add(ElementoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 608, -1, -1));

        ElementTextBox.setEditable(false);
        ElementTextBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ElementTextBoxActionPerformed(evt);
            }
        });
        getContentPane().add(ElementTextBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 600, 140, 30));

        ConfirmButton.setText("Confirmar");
        ConfirmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfirmButtonActionPerformed(evt);
            }
        });
        getContentPane().add(ConfirmButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 640, -1, -1));

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/4.png"))); // NOI18N
        getContentPane().add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ElementTextBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ElementTextBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ElementTextBoxActionPerformed

    private void ConfirmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmButtonActionPerformed
        
    }//GEN-LAST:event_ConfirmButtonActionPerformed

    private void LítioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LítioMouseClicked
        ElementTextBox.setText("Lítio");
    }//GEN-LAST:event_LítioMouseClicked

    private void HidrogênioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HidrogênioMouseClicked
        ElementTextBox.setText("Hidrogênio");
    }//GEN-LAST:event_HidrogênioMouseClicked

    private void SódioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SódioMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_SódioMouseClicked

    private void _CopiaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event__CopiaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event__CopiaMouseClicked

    private void PotássioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PotássioMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_PotássioMouseClicked

    private void RubídioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RubídioMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_RubídioMouseClicked

    private void CésioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CésioMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_CésioMouseClicked

    private void FrâncioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FrâncioMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_FrâncioMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TabelaP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TabelaP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TabelaP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TabelaP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TabelaP().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JButton ConfirmButton;
    private javax.swing.JLabel Césio;
    private javax.swing.JTextField ElementTextBox;
    private javax.swing.JLabel ElementoLabel;
    private javax.swing.JLabel Frâncio;
    private javax.swing.JLabel Hidrogênio;
    private javax.swing.JLabel Lítio;
    private javax.swing.JLabel Potássio;
    private javax.swing.JLabel Rubídio;
    private javax.swing.JLabel Sódio;
    private javax.swing.JLabel _Copia;
    // End of variables declaration//GEN-END:variables
}
